import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0c1017",
        surface: "#13131b",
        "surface-dim": "#13131b",
        "surface-container-low": "#13131b",
        "surface-container": "#1a1f26",
        "surface-container-high": "#252b34",
        "surface-container-highest": "#252b34",
        "surface-bright": "#393841",
        "surface-variant": "#34343d",
        "surface-tint": "#c0c1ff",
        "outline-variant": "#2d333b",
        outline: "#908fa0",
        primary: "#c0c1ff",
        "primary-container": "#8083ff",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary": "#1000a9",
        "on-primary-container": "#0d0096",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        secondary: "#4edea3",
        "secondary-container": "#00a572",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#003824",
        "on-secondary-container": "#00311f",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#ffb95f",
        "tertiary-container": "#ca8100",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary": "#472a00",
        "on-tertiary-container": "#3e2400",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-background": "#e4e1ed",
        "on-surface": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        inverse-surface: "#e4e1ed",
        "inverse-on-surface": "#303038",
        "inverse-primary": "#494bd6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "20px",
        "sidebar-collapsed": "64px",
        "sidebar-width": "240px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "20px", fontWeight: "500" }],
      },
      keyframes: {
        "pulse-check": {
          "0%": { boxShadow: "0 0 0 0 rgba(192, 193, 255, 0.7)" },
          "100%": { boxShadow: "0 0 0 20px rgba(192, 193, 255, 0)" },
        },
        "slide-in-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "pulse-check": "pulse-check 0.5s ease-out",
        "slide-in-up": "slide-in-up 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
} satisfies Config;